#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "**/etc/.*"
    - "**/src/app.js"
    - "**/themes/.*"
    - "**/interfaces/.*"
    - "**/types/.*"
    - "**/routes/.*"
    - "**/.circleci/.*"
    - "**/*.stories.tsx"
    - "**/.storybook/.*"
    - "**/*.spec.tsx"
    - "**/*.spec.ts"
    - "**/*.scss"
    - "**/*.svg"
